
name: CI Back & Front

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: build compose file
       run: cd Back && docker-compose build
     - name: run containers
       run: cd Back && docker-compose up -d
     - name: test docker containers
       run: docker ps -a
     - name: test volume
       run: docker exec php-app ls -al
     - name: composer dependencies
       run: docker exec php-app composer install
        docker-compose exec -T app php bin/console doctrine:migration:migrate
        docker-compose exec -T app php bin/console doctrine:fixtures:load
        docker-compose exec -T app php bin/console doctrine:database:drop --force --env=test
        docker-compose exec -T app php bin/console doctrine:database:create --env=test
        docker-compose exec -T app php bin/console doctrine:migrations:migrate -n --env=test
        docker exec -e XDEBUG_MODE=coverage php-app vendor/bin/phpunit --coverage-text
     - name: phpunit test
       continue-on-error: true
       run: docker exec php-app php bin/phpunit
